blueprint:
  name: "B&O Mozart Expand med Slave Selection (Extract JID fra Slave) v2"
  description: >
    Denne automation udtrækker automatisk JID'en fra de valgte slave-enheder via deres
    "beolink → self" attribut og expanderer master-enheden med den udtrukne liste af JID'er.
  domain: automation
  input:
    master_device:
      name: Master-enhed
      description: "Vælg den B&O Mozart master-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_devices:
      name: Slave-enheder
      description: >
        Vælg de slave-enheder, der skal inkluderes i masterens gruppe.
        JID'erne udtrækkes automatisk fra hver enheds "beolink → self" attribut.
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
          multiple: true
    trigger_state:
      name: Trigger-tilstand
      description: "Den tilstand, som master-enheden skal skifte til for at udløse expand."
      default: "playing"
      selector:
        text:
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
action:
  # Overfør blueprint-input til lokale variabler.
  - variables:
      master: !input master_device
      slaves: !input slave_devices
      slave_jids: >
        {%- set jids = [] -%}
        {%- for slave in slaves -%}
          {%- set attrs = states[slave].attributes -%}
          {%- set beolink = attrs.beolink if attrs.beolink is defined else {} -%}
          {%- set s = beolink.self if beolink.self is defined else {} -%}
          {%- if s and s|length > 0 -%}
            {%- set jlist = s.values() | list -%}
            {%- set j = jlist[0] -%}
            {%- set jids = jids + [ j ] -%}
          {%- endif -%}
        {%- endfor -%}
        {{ jids }}
  # Log alle slave-enhedernes attributter for debugging.
  - service: system_log.write
    data:
      message: >
        Slave devices attributes:
        {%- for slave in slaves -%}
          {{ slave }}: {{ states[slave].attributes | tojson }}
        {%- endfor -%}
      level: info
  # Log de udtrukne JID'er for debugging.
  - service: system_log.write
    data:
      message: "Extracted Slave JIDs: {{ slave_jids }}"
      level: info
  # Kald expand-servicen med master-enhedens entity_id og den udtrukne liste af JID'er.
  - service: bang_olufsen.beolink_expand
    target:
      entity_id: "{{ master }}"
    data_template:
      beolink_jids: "{{ slave_jids }}"
