blueprint:
  name: B&O Mozart Expand – Slave JID fra Slave Device
  description: >
    Når master-enheden skifter til en bestemt tilstand (f.eks. "playing"),
    udtrækkes JID'en fra slave-enhedens 'self'-attribut, og master-enheden expanderes
    med denne JID.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_device:
      name: Slave Device
      description: >
        Vælg den B&O Mozart-enhed, hvorfra JID'en hentes. Blueprintet udtrækker JID'en
        fra enhedens 'self'-attribut (forventes at være et dictionary).
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    trigger_state:
      name: Trigger State
      description: >
        Den tilstand, som master-enheden skal skifte til for at udløse expand-funktionen.
      default: "playing"
      selector:
        text:
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
action:
  # Overfør input til lokale variabler, så de er tilgængelige i templaten.
  - variables:
      master: !input master_device
      slave: !input slave_device
  - service: bang_olufsen.beolink_expand
    target:
      entity_id: "{{ master }}"
    data_template:
      beolink_jids: >
        {% set self_attr = state_attr(slave, 'self') %}
        {% if self_attr %}
          {{ self_attr.values() | list }}
        {% else %}
          []
        {% endif %}
