blueprint:
  name: "Extract Master JID from self with full attributes"
  description: >
    Denne automation logger de fulde attributter for master-enheden og udtrækker JID'en
    fra dens "self"-attribut, når master-enheden skifter til tilstanden "playing".
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart master-enhed, som forventes at indeholde 'self'-attributten."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
trigger:
  - platform: state
    entity_id: !input master_device
    to: "playing"
action:
  - variables:
      master: !input master_device
  # Log alle attributterne for master-enheden.
  - service: system_log.write
    data:
      message: "Full attributes for {{ master }}: {{ states[master].attributes }}"
      level: info
  # Forsøg at udtrække JID'en fra 'self'-attributten.
  - service: system_log.write
    data:
      message: >
        {%- set self_attr = states[master].attributes.self or {} -%}
        {%- if self_attr %}
          Extracted JID(s): {{ self_attr.values() | list }}
        {%- else %}
          No 'self' attribute found.
        {%- endif %}
      level: info
