blueprint:
  name: B&O Mozart Expand - Vælg Peer JIDs
  description: >
    Denne automation udvider en B&O Mozart master-enhed med de JIDs,
    du vælger manuelt. Masteren viser en liste af peers (JIDs) under dens 'peers'-attribut.
    Da Home Assistants blueprint-system ikke understøtter dynamisk genererede dropdowns,
    skal du kopiere den ønskede JID manuelt.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    peer_jids:
      name: Peer JIDs
      description: >
        Angiv de JIDs, der skal tilføjes til masteren. Disse JIDs findes under masterens
        'peers'-attribut. Kopiér den ønskede JID (eller flere) manuelt.
      selector:
        text:
          multiple: true
trigger:
  - platform: state
    entity_id: !input master_device
    to: "playing"
action:
  - service: bang_olufsen.beolink_expand
    target:
      entity_id: !input master_device
    data:
      beolink_jids: !input peer_jids
