blueprint:
  name: B&O Mozart Expand med Slave Peer Selection
  description: >
    Denne automation expanderer en B&O Mozart master-enhed ved at inkludere de valgte slave-enheder.
    Blueprintet udtrækker automatisk JID'erne for de valgte slave-enheder fra masterens "peers"-attribut
    ved at matche slave-enhedernes "friendly_name" med nøglerne i "peers".
  domain: automation
  input:
    master_device:
      name: Master-enhed
      description: "Vælg den B&O Mozart master-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_devices:
      name: Slave-enheder
      description: >
        Vælg en eller flere slave-enheder. Blueprintet matcher hver slave's "friendly_name" med en nøgle
        i masterens "peers"-attribut for at udtrække den tilhørende JID.
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
          multiple: true
    trigger_state:
      name: Trigger-tilstand
      description: >
        Den tilstand, som master-enheden skal skifte til, for at udløse expand-handlingen.
      default: "playing"
      selector:
        text:
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
action:
  # Overfør blueprint-input til lokale variabler
  - variables:
      master: !input master_device
      slaves: !input slave_devices
  # (Valgfrit) Log masterens peers-attribut for debugging
  - service: system_log.write
    data:
      message: "Master peers: {{ state_attr(master, 'peers') }}"
      level: info
  # (Valgfrit) Log de valgte slave-enheders friendly_name for debugging
  - service: system_log.write
    data:
      message: >
        {%- for slave in slaves -%}
          Slave: {{ state_attr(slave, 'friendly_name') }}; 
        {%- endfor -%}
      level: info
  # Udtræk JID'erne fra masterens peers-attribut baseret på slave-enhedernes friendly_name
  - variables:
      stored_jids: >
        {%- set master_peers = state_attr(master, 'peers') or {} -%}
        {%- set jids = [] -%}
        {%- for slave in slaves -%}
          {%- set fname = state_attr(slave, 'friendly_name') -%}
          {%- if fname and master_peers[fname] is defined -%}
            {%- set _ = jids.append(master_peers[fname]) -%}
          {%- endif -%}
        {%- endfor -%}
        {{ jids }}
  # Log de udtrukne JID'er for debugging
  - service: system_log.write
    data:
      message: "Udtrukne JID'er: {{ stored_jids }}"
      level: info
  # Kald expand-servicen med den udtrukne liste af JID'er
  - service: bang_olufsen.beolink_expand
    target:
      entity_id: !var master
    data_template:
      beolink_jids: !var stored_jids
