blueprint:
  name: B&O Mozart Expand – Slave udvalgt som Entity
  description: >
    Når master-enheden skifter til en bestemt tilstand (fx "playing"),
    udtrækkes slave-enhedens JID automatisk fra dens "self"-attribut.
    Masteren expanderes herefter med denne JID.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart master-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_device:
      name: Slave Device
      description: >
        Vælg den B&O Mozart slave-enhed, hvis JID (fundet under 'self')
        skal udtrækkes automatisk.
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    trigger_state:
      name: Trigger State
      description: >
        Den tilstand, som master-enheden skal skifte til for at udløse expansion.
        Eksempel: "playing"
      default: "playing"
      selector:
        text:
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
action:
  # Sæt slave_device ind i en variabel, så den er tilgængelig i templaten
  - variables:
      slave: !input slave_device
  - service: bang_olufsen.beolink_expand
    target:
      entity_id: !input master_device
    data_template:
      beolink_jids: >
        {%- set attr = state_attr(slave, 'self') -%}
        {%- if attr -%}
          {{ attr.values() | list }}
        {%- else -%}
          []
        {%- endif -%}
