blueprint:
  name: "B&O Mozart Expand + (Optional) Volume Sync (Multiple Slave JIDs)"
  description: >
    Denne automation expanderer en B&O Mozart master-enhed ved at tilføje de slave-enheder,
    hvis JID'er indtastes manuelt. Du kan indtaste flere slave‑JID'er.
    Derudover kan du vælge at aktivere volume‑synkronisering, så de valgte slave-enheder får deres volume
    matchet med masterens, når masterens volume ændres.
    Yderligere betingelser (fx tidsbetingelser, andre enhedsbetingelser) kan også angives.
  domain: automation
  input:
    master_device:
      name: "Master Device"
      description: "Vælg den B&O Mozart master-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_jids:
      name: "Slave JIDs"
      description: >
        Indtast JID'er for de slave-enheder, der skal tilføjes til masterens gruppe.
        Fx:
          - 1111.2222222.33333333@products.bang-olufsen.com
          - 4444.5555555.66666666@products.bang-olufsen.com
      selector:
        text:
          multiple: true
    sync_volume:
      name: "Sync Volume?"
      description: >
        Hvis sandt, synkroniseres volume for de valgte slave-enheder med masterens,
        når masterens volume ændres.
      default: false
      selector:
        boolean:
    slave_devices_sync:
      name: "Slave Devices (Volume Sync)"
      description: >
        Vælg de slave-enheder, hvis volume skal synkroniseres med masterens.
        Dette felt bruges kun, hvis "Sync Volume?" er aktiveret.
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
          multiple: true
    trigger_state:
      name: "Trigger State"
      description: >
        Den tilstand, som master-enheden skal skifte til for at udløse expand-handlingen.
      default: "playing"
      selector:
        text:
    conditions:
      name: "Additional Conditions"
      description: >
        Valgfri ekstra betingelser, der skal være opfyldt, før automationen kører.
        Du kan fx tilføje tidsbetingelser, betingelser for andre enheder osv.
      default: []
      selector:
        condition: {}
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
    id: expand_trigger
  - platform: state
    entity_id: !input master_device
    attribute: volume_level
    id: volume_sync_trigger
action:
  - choose:
      # Case 1: Expansion – udløstes når master går til trigger_state (fx "playing")
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'expand_trigger' }}"
          - condition: and
            conditions: !input conditions
        sequence:
          - service: bang_olufsen.beolink_expand
            target:
              entity_id: !input master_device
            data:
              beolink_jids: !input slave_jids
      # Case 2: Volume Sync – udløstes når masterens volume ændres, sync_volume er aktiveret og ekstra betingelser er opfyldte
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'volume_sync_trigger' and sync_volume }}"
          - condition: and
            conditions: !input conditions
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: !input slave_devices_sync
            data:
              volume_level: "{{ trigger.to_state.attributes.volume_level }}"
    default: []
