blueprint:
  name: "Extract Master JID from self with debugging"
  description: >
    Denne automation logger hele master-enhedens tilstand og udtrækker JID'en fra dens "self"‑attribut.
    Hvis attributten ikke findes under "self", forsøges "Self". Se loggen for at kontrollere, om attributten findes.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart master-enhed, som forventes at indeholde JID under 'self'."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
trigger:
  - platform: state
    entity_id: !input master_device
    to: "playing"
action:
  - variables:
      master: !input master_device
  # Log hele state-objektet for master-enheden for debugging.
  - service: system_log.write
    data:
      message: "Full state for {{ master }}: {{ states(master) }}"
      level: info
  # Forsøg at udtrække JID'en fra enten 'self' eller 'Self'.
  - service: system_log.write
    data:
      message: >
        {%- set self_attr = state_attr(master, 'self') or state_attr(master, 'Self') or {} -%}
        Extracted self attribute: {{ self_attr }}.
        {% if self_attr %}
          Extracted JID(s): {{ self_attr.values() | list }}
        {% else %}
          No self attribute found.
        {% endif %}
      level: info
