blueprint:
  name: B&O Mozart – Expand + (Optional) Volume Sync (Multi-Slave)
  description: >
    1) Automatically expand a B&O Mozart master device by adding one or more 
       devices (via JIDs) when the master enters a chosen state (e.g. playing).
    2) If enabled, also sync the volumes of the slave devices to the master's.
    3) Conditions can be set to restrict when the automation runs.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "The B&O Mozart speaker that will expand and optionally control volume."
      selector:
        entity:
          integration: bang_olufsen
          domain: media_player
    slave_devices:
      name: Slave Devices (for Volume Sync)
      description: >
        The B&O Mozart speakers to be added to the master’s group,
        and optionally have their volumes synced to the master's.
      selector:
        entity:
          integration: bang_olufsen
          domain: media_player
          multiple: true
    slave_jids:
      name: Slave JIDs
      description: >
        List of JIDs of the devices to be added when the master expands.
        For example:
          - 1111.2222222.33333333@products.bang-olufsen.com
          - 4444.5555555.66666666@products.bang-olufsen.com
      default: []
      selector:
        text:
          multiple: true
    trigger_condition:
      name: Trigger Condition
      description: >
        The master's state that triggers expansion (commonly "playing" or "on").
      selector:
        select:
          options:
            - "playing"
            - "on"
    sync_volume:
      name: Sync Volume?
      description: >
        If true, whenever the master's volume changes, 
        set the slave devices' volumes to match.
      default: false
      selector:
        boolean:
    conditions:
      name: Additional Conditions
      description: >
        Optional conditions that must be met before the automation runs.
        For example: Only trigger if it's between certain hours, 
        or if another sensor is in a specific state.
      default: []
      selector:
        condition: {}

trigger:
  # Trigger A: Expand when the master changes to the specified trigger_condition
  - platform: state
    entity_id: !input master_device
    to: !input trigger_condition
    id: expand_trigger
  # Trigger B: Volume sync whenever the master’s volume changes (attribute: volume_level)
  - platform: state
    entity_id: !input master_device
    attribute: volume_level
    id: volume_sync_trigger

variables:
  # Store whether volume sync is enabled
  is_sync_volume: !input sync_volume

action:
  - choose:
      # -- Case 1: Expansion – if the expand_trigger fired and conditions are met
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'expand_trigger' }}"
          - condition: and
            conditions: !input conditions
        sequence:
          - service: bang_olufsen.beolink_expand
            target:
              entity_id: !input master_device
            data:
              beolink_jids: !input slave_jids
      # -- Case 2: Volume Sync – if the volume_sync_trigger fired, sync_volume is true, and conditions are met
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'volume_sync_trigger' and is_sync_volume }}"
          - condition: and
            conditions: !input conditions
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: !input slave_devices
            data:
              volume_level: "{{ trigger.to_state.attributes.volume_level }}"
    default: []