blueprint:
  name: "Extract Master JID"
  description: >
    Denne automation udtrækker JID'erne fra master-enhedens "peers"-attribut
    og logger dem til systemloggen.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart master-enhed, som indeholder 'peers'-attributten."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
trigger:
  - platform: state
    entity_id: !input master_device
    to: "playing"
action:
  - variables:
      master: !input master_device
  - service: system_log.write
    data:
      message: >
        {%- set peers = state_attr(master, 'peers') or {} -%}
        {%- if peers -%}
          Extracted JIDs: {{ peers.values() | list }}
        {%- else -%}
          No peers found.
        {%- endif -%}
      level: info
