blueprint:
  name: "B&O Mozart Expand + (Optional) Volume Sync (Manuel Slave JID)"
  description: >
    Denne automation expanderer en B&O Mozart master-enhed ved at tilføje en slave‑enhed,
    hvis JID indtastes manuelt. Derudover kan du vælge at aktivere volume‑synkronisering,
    så slave‑enhedens volume matches med masterens, når masterens volume ændres.
  domain: automation
  input:
    master_device:
      name: Master-enhed
      description: "Vælg den B&O Mozart master-enhed, der skal expanderes."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_jid:
      name: Slave JID
      description: >
        Indtast JID for den slave-enhed, der skal tilføjes til masterens gruppe.
        Fx: 1111.2222222.33333333@products.bang-olufsen.com
      selector:
        text:
    sync_volume:
      name: "Synkroniser Volume?"
      description: >
        Hvis sandt, synkroniseres slave-enhedens volume med masterens,
        når masterens volume ændres.
      default: false
      selector:
        boolean:
    slave_device:
      name: "Slave-enhed (Volume Sync)"
      description: >
        Vælg den slave-enhed, hvis volume skal synkroniseres med masterens.
        (Dette felt er kun relevant, hvis "Synkroniser Volume?" er aktiveret.)
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    trigger_state:
      name: "Trigger-tilstand"
      description: >
        Den tilstand, som master-enheden skal skifte til for at udløse expand-handlingen.
      default: "playing"
      selector:
        text:
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
    id: expand_trigger
  - platform: state
    entity_id: !input master_device
    attribute: volume_level
    id: volume_sync_trigger
action:
  - choose:
      # Case 1: Expansion – når master skifter til den angivne tilstand
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'expand_trigger' }}"
        sequence:
          - service: bang_olufsen.beolink_expand
            target:
              entity_id: !input master_device
            data:
              beolink_jids:
                - !input slave_jid
      # Case 2: Volume Sync – når masterens volume ændres, og synkronisering er aktiveret
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'volume_sync_trigger' and sync_volume }}"
        sequence:
          - service: media_player.volume_set
            target:
              entity_id: !input slave_device
            data:
              volume_level: "{{ trigger.to_state.attributes.volume_level }}"
    default: []
