blueprint:
  name: "Extract Master JID from beolink.self"
  description: >
    Denne automation logger alle attributter for master-enheden og udtrækker JID'erne
    fra dens "beolink → self"-attribut, når enheden går til tilstanden "playing".
  domain: automation
  input:
    master_device:
      name: Master Device
      description: >
        Vælg den B&O Mozart master-enhed, som forventes at indeholde JID'en under
        beolink → self.
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
trigger:
  - platform: state
    entity_id: !input master_device
    to: "playing"
action:
  - variables:
      master: !input master_device
  # Log alle attributterne for master-enheden for at se, hvad der er tilgængeligt.
  - service: system_log.write
    data:
      message: "Full attributes for {{ master }}: {{ states[master].attributes }}"
      level: info
  # Udtræk og log JID'erne fra beolink.self
  - service: system_log.write
    data:
      message: >
        {%- set beolink_attr = states[master].attributes.beolink or {} -%}
        {%- set self_attr = beolink_attr.self or {} -%}
        {%- if self_attr %}
          Extracted JID(s): {{ self_attr.values() | list }}
        {%- else %}
          No 'beolink.self' attribute found.
        {%- endif %}
      level: info
