blueprint:
  name: B&O Mozart Expand Simple
  description: >
    Når master-enheden skifter til en bestemt tilstand (f.eks. "playing"),
    udtrækkes JID’en fra slave-enhedens 'self'-attribut, og masteren udvides
    til at inkludere slave-enheden.
  domain: automation
  input:
    master_device:
      name: Master Device
      description: "Vælg den B&O Mozart-enhed, der skal udvides."
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    slave_device:
      name: Slave Device
      description: >
        Vælg den B&O Mozart-enhed, hvis JID (fundet under 'self') skal hentes og bruges
        til udvidelse.
      selector:
        entity:
          domain: media_player
          integration: bang_olufsen
    trigger_state:
      name: Trigger State
      description: >
        Den tilstand, som master-enheden skal skifte til for at udløse udvidelsen.
      default: "playing"
      selector:
        text:
trigger:
  - platform: state
    entity_id: !input master_device
    to: !input trigger_state
action:
  - service: bang_olufsen.beolink_expand
    target:
      entity_id: !input master_device
    data_template:
      beolink_jids: >
        {% set attr = state_attr(slave_device, 'self') %}
        {% if attr %}
          {{ attr.values() | list }}
        {% else %}
          []
        {% endif %}
